name: Python

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  workflow_dispatch:

jobs:
  python-sdist:
    name: python sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init extlib/mimalloc extlib/eigen
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Pack
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            version="${GITHUB_REF##*/}"
          else
            mkdir empty-build
            cd empty-build
            cmake .. -DENABLE_GUI=OFF -DENABLE_CLI=OFF -DENABLE_TESTS=OFF -DENABLE_COVERAGE=OFF -DENABLE_SANITIZERS=OFF -DENABLE_OPENMP=OFF
            source version.env
            cd ..
            version="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.dev${GITHUB_RUN_NUMBER}"
          fi
          sed -i.bak "s/^version = .*/version = \"${version}\"/g" pyproject.toml && rm pyproject.toml.bak
          python -m pip install -U setuptools build
          python -m build --sdist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: dist/*.tar.gz

  python-wheel:
    name: ${{ matrix.os_short }} python ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os_short: linux
            architecture: x86_64
            cibuildwheel_architecture: x86_64
          - os: macos-latest
            os_short: macos
            architecture: universal2
            cibuildwheel_architecture: universal2
          - os: windows-latest
            os_short: win
            architecture: amd64
            cibuildwheel_architecture: AMD64
            cmake_generator_platform: x64

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init extlib/mimalloc extlib/eigen
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_ARCHS: "${{ matrix.cibuildwheel_architecture }}"
          # Rest of your existing environment variables...

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          # This saves each platform's wheels into a single "python-wheels" folder
          name: python-wheels-${{ matrix.os_short }}-${{ matrix.architecture }}
          path: ./wheelhouse/*.whl
